import { useState } from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowDownRight, ArrowUpRight, Mail, Menu, X } from 'lucide-react'
import './styles.css'

const projects = [
  ['01','Data science / 2026','Human Vital Sign','Classifying health risk from clinical records to make proactive monitoring more practical.','25,000+ records processed with Python, Pandas, and SQL. Compared Decision Tree, Logistic Regression, and KNN models.',['25K+ records','3 models compared'],['Python','Pandas','SQL','Machine Learning'],'mint'],
  ['02','Mobile product / 2020','MediCare','A connected patient record experience designed to reduce hospital paperwork.','A final-year capstone bringing medical history, lab results, treatment, and appointments into one mobile workflow.',['1 unified record','Kotlin + Firebase'],['Kotlin','Node.js','Firebase'],'sky'],
  ['03','Marketplace / 2019','HawFarm','Helping farmers sell fresh produce directly to their customers.','An Android marketplace that removes third-party barriers with a mobile-first buying and selling experience.',['Direct marketplace','Android native app'],['Java','Android','Firebase'],'coral'],
]
const capabilities = [['01','Data analysis','Python, SQL, Pandas, Jupyter'],['02','Machine learning','Classification, evaluation, feature engineering'],['03','Data visualization','Power BI, Databricks, clear storytelling'],['04','Product development','React Native, Kotlin, Swift, Firebase']]

function App() {
  const [open,setOpen]=useState(false); const nav=['Work','Profile','Capabilities','Contact']
  return <main>
    <header><a className="brand" href="#top">A<span>·</span>P</a><nav>{nav.map(x=><a key={x} href={'#'+x.toLowerCase()}>{x}</a>)}</nav><div className="actions"><a className="resume" href="/Aatish-Patel-Resume.pdf" download>Résumé <ArrowDownRight size={15}/></a><a className="hello" href="mailto:amp70468@gmail.com">Say hello</a></div><button className="toggle" onClick={()=>setOpen(!open)} aria-label="Menu">{open?<X/>:<Menu/>}</button></header>
    {open&&<div className="mobileNav">{nav.map(x=><a key={x} onClick={()=>setOpen(false)} href={'#'+x.toLowerCase()}>{x}</a>)}<a href="/Aatish-Patel-Resume.pdf" download>Download résumé</a></div>}
    <section id="top" className="hero"><div className="heroCopy"><p className="availability"><i/> Open to opportunities</p><p className="kicker">Data analyst · Software developer<br/>Toronto, Canada</p><h1>Making data<br/><em>useful.</em></h1><p className="intro">I design analytical and software solutions that turn complex information into simple, actionable decisions.</p><a className="explore" href="#work">Explore selected work <b><ArrowDownRight size={18}/></b></a></div><div className="heroArt"><div className="orbit one"/><div className="orbit two"/><div className="dots"/><div className="focus">FOCUS<strong>Data<br/>+ people</strong></div><div className="now">NOW<strong>2026</strong></div><div className="mono">AP</div></div><div className="heroFoot"><span>Scroll to discover</span><i/><span>Portfolio / 01</span></div></section>
    <section id="work" className="work"><div className="sectionHead"><div><p className="label">Selected work</p><h2>Built to make a<br/><em>difference.</em></h2></div><p>Thoughtful projects at the intersection<br/>of data, technology, and daily life.</p></div><div className="projects">{projects.map((p,i)=><article className={'project '+p[7]} key={p[0]}><div className="meta"><span>{p[0]}</span><span>{p[1]}</span><ArrowUpRight size={18}/></div><div className="projectMain"><div><h3>{p[2]}</h3><p>{p[3]}</p></div><b className="symbol">{i===0?'✦':i===1?'+':'◒'}</b></div><div className="projectBottom"><p>{p[4]}</p><div className="metrics">{p[5].map(m=><b key={m}>{m}</b>)}</div><div className="tags">{p[6].map(t=><span key={t}>{t}</span>)}</div></div></article>)}</div></section>
    <section id="profile" className="profile"><p className="label">A little about me</p><div className="profileGrid"><div className="stamp"><span>ANALYZE</span><span>BUILD</span><span>IMPROVE</span><b>AP</b></div><div><h2>I connect the <em>what</em><br/>with the <em>why.</em></h2><p>My background combines data analytics, mobile application development, and computer engineering. I enjoy untangling a difficult problem, building a useful solution, and showing the people behind it what the result means.</p><div className="links"><a href="https://github.com/aatish70468" target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={16}/></a><a href="https://linkedin.com/in/aatish-patel138" target="_blank" rel="noreferrer">LinkedIn <ArrowUpRight size={16}/></a></div></div></div></section>
    <section id="capabilities" className="capabilities"><div><p className="label">Capabilities</p><h2>A practical<br/><em>toolkit.</em></h2><p className="capIntro">From exploration to implementation, I bring a structured, curious approach to solving problems.</p></div><div className="capList">{capabilities.map(c=><div key={c[0]}><span>{c[0]}</span><h3>{c[1]}</h3><p>{c[2]}</p><ArrowUpRight size={18}/></div>)}</div></section>
    <section className="education"><div><span>EDUCATION</span><p>Post-Graduate Certificate<br/><strong>Data Analytics</strong> · Humber Polytechnic</p></div><div><span>PREVIOUSLY</span><p>Mobile App Development · George Brown<br/>B.E. Computer Engineering · GTU</p></div><b>2024—26</b></section>
    <footer id="contact"><p className="label">Start a conversation</p><a href="mailto:amp70468@gmail.com">Let’s work<br/><em>together.</em> <ArrowUpRight/></a><div className="foot"><span>© 2026 Aatish Patel</span><a href="mailto:amp70468@gmail.com"><Mail size={14}/>amp70468@gmail.com</a><span>Toronto, Canada</span></div></footer>
  </main>
}
createRoot(document.getElementById('root')).render(<App />)
